effect_to_ingredients_dict = \
    {'Uleczenie choroby': {'Zwęglona skóra ślizgacza (Charred Skeever Hide)', 'Jastrzębie pióra (Hawk Feathers)',
                           'Pancerzyk kraba błotnego (Mudcrab Chitin)', 'Wampirzy pył (Vampire Dust)'},
     'Osłabienie zdrowia': {'Szkarłatny korzeń nirnu (Crimson Nirnroot)', 'Dzwonecznik Kostuchy (Deathbell)',
                            'Ektoplazma (Ectoplasm)', 'Ucho Falmera (Falmer Ear)', 'Ludzkie mięso (Human Flesh)',
                            'Ludzkie serce (Human Heart)', 'Stolec chochlika (Imp Stool)', 'Korzeń jarrin (Jarrin Root)',
                            'Psianka (Nightshade)', 'Korzeń nirnu (Nirnroot)',
                            'Czerwony kwiat górski (Red Mountain Flower)',
                            'Rzeczna becia (River Betty)', 'Ogon ślizgacza (Skeever Tail)',
                            'Małe poroże (Small Antlers)',
                            'Łój trolla (Troll Fat)', 'Sole pustki (Void Salts)'},
     'Osłabienie magii': {'Motyle skrzydło (Butterfly Wing)', 'Jaja chaurusa (Chaurus Eggs)',
                          'Serce Daedry (Daedra Heart)', 'Oko kota szablozębnego (Eye of Sabre Cat)',
                          'Lśniącopył (Glow Dust)', 'Pióra wiedźmokruka (Hagraven Feathers)',
                          'Wiszący mech (Hanging Moss)', 'Ludzkie serce (Human Heart)', 'Korzeń jarrin (Jarrin Root)',
                          'Skrzydło księżycowej ćmy (Luna Moth Wing)', 'Gnilec Namiry (Namira’s Rot)',
                          'Norska Pękla (Nordic Barnacle)'},
     'Osłabienie regeneracji magii': {'Pazury niedźwiedzia (Bear Claws)',
                                      'Skrzydło niebieskiego motyla (Blue Butterfly Wing)',
                                      'Niebieski kwiat górski (Blue Mountain Flower)',
                                      'Kurze jajo (Chicken’s Egg)', 'Lśniącopył (Glow Dust)',
                                      'Wiszący mech (Hanging Moss)', 'Ludzkie serce (Human Heart)',
                                      'Korzeń jarrin (Jarrin Root)', 'Psianka (Nightshade)', 'Pajęcze jajo (Spider Egg)',
                                      'Posoka wiły (Spriggan Sap)'},
     'Osłabienie kondycji': {'Pęcherzyca (Blisterwort)', 'Skrzydło niebieskiego motyla (Blue Butterfly Wing)',
                             'Maczka kostna (Bone Meal)', 'Wilczy korzeń (Canis Root)',
                             'Szkarłatny korzeń nirnu (Crimson Nirnroot)', 'Cyrodiilska ogonnica (Cyrodilic Spadetail)',
                             'Paluch giganta (Giant’s Toe)', 'Korzeń jarrin (Jarrin Root)', 'Korzeń nirnu (Nirnroot)',
                             'Jajo skałoświerga (Rock Warbler Egg)', 'Pajęcze jajo (Spider Egg)'},
     'Osłabienie regeneracji kondycji': {'Kępa pełzanicy (Creep Cluster)', 'Serce Daedry (Daedra Heart)',
                                         'Mroźna mirriam (Frost Mirriam)', 'Paluch giganta (Giant’s Toe)',
                                         'Histokarp (Histcarp)', 'Jagody jałowca (Juniper Berries)',
                                         'Duże poroże (Large Antlers)', 'Okoń srebrnoboczny (Silverside Perch)',
                                         'Ogon ślizgacza (Skeever Tail)', 'Pszenica (Wheat)'},
     'Strach': {'Niebieski ostroskrzydlak (Blue Dartwing)', 'Cyrodiilska ogonnica (Cyrodilic Spadetail)',
                'Serce Daedry (Daedra Heart)', 'Gnilec Namiry (Namira’s Rot)',
                'Starty kieł mamuta (Powdered Mammoth Tusk)'},
     'Premia do Przemiany': {'Trawiak (Grass Pod)', 'Rzeczna becia (River Betty)', 'Posoka wiły (Spriggan Sap)'},
     'Premia do Retoryki': {'Motyle skrzydło (Butterfly Wing)', 'Smoczy język (Dragon’s Tongue)',
                            'Szpon wiedźmokruka (Hagraven Claw)', 'Śnieżna bawełna (Tundra cotton)'},
     'Premia do Bloku': {'Krwawiąca korona (Bleeding Crown)', 'Serce róży (Briar Heart)', 'Plaster miodu (Honeycomb)',
                         'Perła (Pearl)', 'Łuski zębacza (Slaughterfish Scales)', 'Śnieżna bawełna (Tundra cotton)'},
     'Premia do Udźwigu': {'Kępa pełzanicy (Creep Cluster)', 'Paluch giganta (Giant’s Toe)',
                           'Dziób jastrzębia (Hawk Beak)', 'Rzeczna becia (River Betty)', 'Łuskwiak (Scaly Pholiota)',
                           'Okład z ognika (Wisp Wrappings)'},
     'Premia do Przyzywania': {'Skrzydło niebieskiego motyla (Blue Butterfly Wing)',
                               'Niebieski kwiat górski (Blue Mountain Flower)',
                               'Maczka kostna (Bone Meal)',
                               'Sole mrozu (Frost Salts)',
                               'Pióra wiedźmokruka (Hagraven Feathers)', 'Lawenda (Lavender)'},
     'Premia do Zniszczenia': {'Skorupa ula (Beehive Husk)', 'Ektoplazma (Ectoplasm)', 'Lśniącopył (Glow Dust)',
                               'Świecące grzyby (Glowing Mushroom)', 'Psianka (Nightshade)',
                               'Okład z ognika (Wisp Wrappings)'},
     'Premia do Zaklinania': {'Skrzydło niebieskiego motyla (Blue Butterfly Wing)', 'Szpon wiedźmokruka (Hagraven Claw)',
                              'Śnieżynki (Snowberries)', 'Posoka wiły (Spriggan Sap)'},
     'Premia do Zdrowia': {'Pazury niedźwiedzia (Bear Claws)', 'Niebieski kwiat górski (Blue Mountain Flower)',
                           'Paluch giganta (Giant’s Toe)', 'Świecące grzyby (Glowing Mushroom)',
                           'Wiszący mech (Hanging Moss)', 'Pszenica (Wheat)'},
     'Premia do Ciężkiego Pancerza': {'Zęby lodowego upiora (Ice Wraith Teeth)',
                                      'Ząb kota szablozębnego (Sabre Cat Tooth)',
                                      'Łuski zębacza (Slaughterfish Scales)', 'Gałązka ostu (Thistle Branch)',
                                      'Biały kapelusz (White Cap)'},
     'Premia do Iluzji': {'Smoczy język (Dragon’s Tongue)', 'Krasnoludzki olej (Dwarven Oil)', 'Mora Tapinella',
                          'Łuskwiak (Scaly Pholiota)', 'Korzeń palowy (Taproot)'},
     'Premia do Lekkiej Zbroi': {'Skorupa ula (Beehive Husk)', 'Jastrzębie pióra (Hawk Feathers)',
                                 'Plaster miodu (Honeycomb)', 'Skrzydło księżycowej ćmy (Luna Moth Wing)',
                                 'Ogon ślizgacza (Skeever Tail)'},
     'Premia do Otwierania Zamków': {'Ucho Falmera (Falmer Ear)', 'Gnilec Namiry (Namira’s Rot)',
                                     'Jajo drozda (Pine Thrush Egg)', 'Pajęcze jajo (Spider Egg)'},
     'Premia do Magii': {'Serce róży (Briar Heart)', 'Ektoplazma (Ectoplasm)', 'Histokarp (Histcarp)',
                         'Winogrona Jazbay (Jazbay Grapes)', 'Czerwony kwiat górski (Red Mountain Flower)',
                         'Śnieżna bawełna (Tundra cotton)', 'Sole pustki (Void Salts)'},
     'Premia do Strzelectwa': {'Wilczy korzeń (Canis Root)', 'Elfie ucho (Elves Ear)',
                               'Jagody jałowca (Juniper Berries)', 'Pajęcze jajo (Spider Egg)'},
     'Premia do Bronii Jednoręcznej': {'Pazury niedźwiedzia (Bear Claws)', 'Wilczy korzeń (Canis Root)',
                                       'Wiszący mech (Hanging Moss)', 'Jastrzębie pióra (Hawk Feathers)',
                                       'Jajo skałoświerga (Rock Warbler Egg)', 'Mała perła (Small Pearl)'},
     'Premia do Kradzieży': {'Niebieski ostroskrzydlak (Blue Dartwing)', 'Norska Pękla (Nordic Barnacle)',
                             'Pomarańczowy ostroskrzydlak (Orange Dartwing)', 'Jajo zębacza (Slaughterfish Egg)'},
     'Premia do Przywracania': {'Abaceański długopłetwiak (Abecean Longfin)',
                                'Cyrodiilska ogonnica (Cyrodilic Spadetail)', 'Sól (Salt Pile)',
                                'Małe poroże (Small Antlers)', 'Mała perła (Small Pearl)'},
     'Premia do Kowalstwa': {'Pęcherzyca (Blisterwort)', 'Świecące grzyby (Glowing Mushroom)',
                             'Ząb kota szablozębnego (Sabre Cat Tooth)', 'Posoka wiły (Spriggan Sap)'},
     'Premia do Skradania': {'Abaceański długopłetwiak (Abecean Longfin)', 'Skorupa ula (Beehive Husk)',
                             'Mroźna mirriam (Frost Mirriam)', 'Jastrzębie pióra (Hawk Feathers)',
                             'Ludzkie mięso (Human Flesh)', 'Starty kieł mamuta (Powdered Mammoth Tusk)',
                             'Purpurowy kwiat górski (Purple Mountain Flower)'},
     'Premia do Kondycji': {'Jaja chaurusa (Chaurus Eggs)', 'Czosnek (Garlic)', 'Duże poroże (Large Antlers)',
                            'Lawenda (Lavender)', 'Jajo zębacza (Slaughterfish Egg)',
                            'Tułów pochodnika (Torchbug Thorax)'},
     'Premia do Broni Dwuręcznej': {'Smoczy język (Dragon’s Tongue)', 'Muchomor czerwony (Fly Amanita)',
                                    'Łój trolla (Troll Fat)'},
     'Szał': {'Pęcherzyca (Blisterwort)', 'Ucho Falmera (Falmer Ear)', 'Muchomor czerwony (Fly Amanita)',
              'Pióra wiedźmokruka (Hagraven Feathers)', 'Ludzkie serce (Human Heart)', 'Łój trolla (Troll Fat)'},
     'Niewidzialność': {'Jaja chaurusa (Chaurus Eggs)', 'Szkarłatny korzeń nirnu (Crimson Nirnroot)',
                        'Zęby lodowego upiora (Ice Wraith Teeth)', 'Skrzydło księżycowej ćmy (Luna Moth Wing)',
                        'Korzeń nirnu (Nirnroot)', 'Wampirzy pył (Vampire Dust)'},
     'Przewlekłe osłabienie zdrowia': {'Stolec chochlika (Imp Stool)', 'Mora Tapinella',
                                       'Pomarańczowy ostroskrzydlak (Orange Dartwing)',
                                       'Jajo zębacza (Slaughterfish Egg)', 'Łuski zębacza (Slaughterfish Scales)'},
     'Przewlekłe osłabienie magii': {'Szpon wiedźmokruka (Hagraven Claw)',
                                     'Fioletowy kwiat górski (Purple Mountain Flower)',
                                     'Bagienna grzybnia (Swamp Fungal Pod)', 'Tułów pochodnika (Torchbug Thorax)',
                                     'Pszenica (Wheat)'},
     'Przewlekłe osłabienie kondycji': {'Motyle skrzydło (Butterfly Wing)', 'Kurze jajo (Chicken’s Egg)',
                                        'Psianka (Nightshade)', 'Małe poroże (Small Antlers)'},
     'Paraliż': {'Serce róży (Briar Heart)', 'Wilczy korzeń (Canis Root)', 'Ludzkie mięso (Human Flesh)',
                 'Stolec chochlika (Imp Stool)', 'Bagienna grzybnia (Swamp Fungal Pod)'},
     'Wyniszczenie Zdrowia': {'Cyrodiilska ogonnica (Cyrodilic Spadetail)', 'Oko kota szablozębnego (Eye of Sabre Cat)',
                              'Olbrzymi porost (Swamp Fungal Pod)', 'Winogrona Jazbay (Jazbay Grapes)',
                              'Okoń srebrnoboczny (Silverside Perch)', 'Ogon ślizgacza (Skeever Tail)'},
     'Wyniszczenie magii': {'Mroźna mirriam (Frost Mirriam)', 'Trawiak (Grass Pod)', 'Lawenda (Lavender)',
                            'Pomarańczowy ostroskrzydlak (Orange Dartwing)',
                            'Czerwony kwiat górski (Red Mountain Flower)', 'Biały kapelusz (White Cap)'},
     'Wyniszczenie Kondycji': {'Pszczoła (Bee)', 'Maczka kostna (Bone Meal)', 'Dzwonecznik Kostuchy (Deathbell)',
                               'Plaster miodu (Honeycomb)', 'Gałązka ostu (Thistle Branch)'},
     'Regeneracja zdrowia': {'Czosnek (Garlic)', 'Jagody jałowca (Juniper Berries)',
                             'Skrzydło księżycowej ćmy (Luna Moth Wing)', 'Gnilec Namiry (Namira’s Rot)',
                             'Norska Pękla (Nordic Barnacle)', 'Wampirzy pył (Vampire Dust)'},
     'Regeneracja Magii': {'Krasnoludzki olej (Dwarven Oil)', 'Sole ognia (Fire Salts)', 'Czosnek (Garlic)',
                           'Winogrona Jazbay (Jazbay Grapes)', 'Księżycowy cukier (Moon Sugar)', 'Sól (Salt Pile)',
                           'Korzeń palowy (Taproot)'},
     'Regeneracja Kondycji': {'Pszczoła (Bee)', 'Muchomor czerwony (Fly Amanita)', 'Mora Tapinella',
                              'Łuskwiak (Scaly Pholiota)'},
     'Odporność na ogień': {'Maczka kostna (Bone Meal)', 'Smoczy język (Dragon’s Tongue)', 'Elfie ucho (Elves Ear)',
                            'Sole ognia (Fire Salts)', 'Muchomor czerwony (Fly Amanita)',
                            'Pancerzyk kraba błotnego (Mudcrab Chitin)', 'Śnieżynki (Snowberries)'},
     'Odporność na zimno': {'Mroźna mirriam (Frost Mirriam)', 'Sole mrozu (Frost Salts)', 'Dziób jastrzębia (Hawk Beak)',
                            'Księżycowy cukier (Moon Sugar)', 'Fioletowy kwiat górski (Purple Mountain Flower)',
                            'Okoń srebrnoboczny (Silverside Perch)', 'Łuski zębacza (Slaughterfish Scales)',
                            'Mała perła (Small Pearl)', 'Śnieżynki (Snowberries)', 'Gałązka ostu (Thistle Branch)'},
     'Odporność na magię': {'Krwawiąca korona (Bleeding Crown)', 'Kurze jajo (Chicken’s Egg)',
                            'Szkarłatny korzeń nirnu (Crimson Nirnroot)', 'Szpon wiedźmokruka (Hagraven Claw)',
                            'Lawenda (Lavender)', 'Korzeń nirnu (Nirnroot)', 'Śnieżna bawełna (Tundra cotton)',
                            'Sole pustki (Void Salts)', 'Okład z ognika (Wisp Wrappings)'},
     'Odporność na trucizny': {'Skorupa ula (Beehive Husk)', 'Zwęglona skóra ślizgacza (Charred Skeever Hide)',
                               'Ucho Falmera (Falmer Ear)', 'Czosnek (Garlic)', 'Trawiak (Grass Pod)',
                               'Pancerzyk kraba błotnego (Mudcrab Chitin)', 'Jajo zębacza (Slaughterfish Egg)',
                               'Gałązka ostu (Thistle Branch)', 'Łój trolla (Troll Fat)'},
     'Odporność na porażenie': {'Niebieski ostroskrzydlak (Blue Dartwing)', 'Lśniącopył (Glow Dust)',
                                'Świecące grzyby (Glowing Mushroom)', 'Dziób jastrzębia (Hawk Beak)', 'Perła (Pearl)',
                                'Jajo drozda (Pine Thrush Egg)', 'Śnieżynki (Snowberries)',
                                'Bagienna grzybnia (Swamp Fungal Pod)'},
     'Przywrócenie Zdrowia': {'Pęcherzyca (Blisterwort)', 'Niebieski ostroskrzydlak (Blue Dartwing)',
                              'Niebieski kwiat górski (Blue Mountain Flower)', 'Motyle skrzydło (Butterfly Wing)',
                              'Zwęglona skóra ślizgacza (Charred Skeever Hide)', 'Serce Daedry (Daedra Heart)',
                              'Oko kota szablozębnego (Eye of Sabre Cat)', 'Stolec chochlika (Imp Stool)',
                              'Jajo skałoświerga (Rock Warbler Egg)', 'Bagienna grzybnia (Swamp Fungal Pod)',
                              'Pszenica (Wheat)'},
     'Przywrócenie magii': {'Serce róży (Briar Heart)', 'Kępa pełzanicy (Creep Cluster)',
                            'Krasnoludzki olej (Dwarven Oil)', 'Ektoplazma (Ectoplasm)', 'Elfie ucho (Elves Ear)',
                            'Sole ognia (Fire Salts)', 'Sole mrozu (Frost Salts)', 'Olbrzymi porost (Swamp Fungal Pod)',
                            'Trawiak (Grass Pod)', 'Ludzkie mięso (Human Flesh)', 'Księżycowy cukier (Moon Sugar)',
                            'Mora Tapinella', 'Perła (Pearl)', 'Czerwony kwiat górski (Red Mountain Flower)',
                            'Korzeń palowy (Taproot)', 'Wampirzy pył (Vampire Dust)', 'Biały kapelusz (White Cap)'},
     'Przywrócenie kondycji': {'Pazury niedźwiedzia (Bear Claws)', 'Pszczoła (Bee)',
                               'Zwęglona skóra ślizgacza (Charred Skeever Hide)',
                               'Oko kota szablozębnego (Eye of Sabre Cat)',
                               'Dziób jastrzębia (Hawk Beak)', 'Histokarp (Histcarp)', 'Plaster miodu (Honeycomb)',
                               'Duże poroże (Large Antlers)', 'Pancerzyk kraba błotnego (Mudcrab Chitin)',
                               'Pomarańczowy ostroskrzydlak (Orange Dartwing)', 'Perła (Pearl)',
                               'Jajo drozda (Pine Thrush Egg)', 'Starty kieł mamuta (Powdered Mammoth Tusk)',
                               'Fioletowy kwiat górski (Purple Mountain Flower)',
                               'Ząb kota szablozębnego (Sabre Cat Tooth)', 'Okoń srebrnoboczny (Silverside Perch)',
                               'Mała perła (Small Pearl)', 'Tułów pochodnika (Torchbug Thorax)',
                               'Okład z ognika (Wisp Wrappings)'},
     'Spowolnienie': {'Dzwonecznik Kostuchy (Deathbell)', 'Duże poroże (Large Antlers)', 'Rzeczna becia (River Betty)',
                      'Sól (Salt Pile)'},
     'Oddychanie pod wodą': {'Kurze jajo (Chicken’s Egg)', 'Histokarp (Histcarp)', 'Norska Pękla (Nordic Barnacle)'},
     'Podatność na ogień' : {'Krwawiąca korona (Bleeding Crown)', 'Sole mrozu (Frost Salts)',
                             'Zęby lodowego upiora (Ice Wraith Teeth)', 'Jagody jałowca (Juniper Berries)',
                             'Księżycowy cukier (Moon Sugar)', 'Starty kieł mamuta (Powdered Mammoth Tusk)'},
     'Podatność na zimno': {'Abaceański długopłetwiak (Abecean Longfin)', 'Elfie ucho (Elves Ear)',
                            'Sole ognia (Fire Salts)', 'Zęby lodowego upiora (Ice Wraith Teeth)',
                            'Biały kapelusz (White Cap)'},
     'Podatność na magię': {'Kępa pełzanicy (Creep Cluster)', 'Krasnoludzki olej (Dwarven Oil)',
                            'Winogrona Jazbay (Jazbay Grapes)', 'Jajo skałoświerga (Rock Warbler Egg)',
                            'Sól (Salt Pile)', 'Łuskwiak (Scaly Pholiota)', 'Korzeń palowy (Taproot)',
                            'Tułów pochodnika (Torchbug Thorax)'},
     'Podatność na trucizny': {'Abaceański długopłetwiak (Abecean Longfin)', 'Krwawiąca korona (Bleeding Crown)',
                               'Jaja chaurusa (Chaurus Eggs)', 'Dzwonecznik Kostuchy (Deathbell)',
                               'Olbrzymi porost (Swamp Fungal Pod)', 'Jajo drozda (Pine Thrush Egg)',
                               'Ząb kota szablozębnego (Sabre Cat Tooth)', 'Małe poroże (Small Antlers)'},
     'Podatność na porażenie': {'Pszczoła (Bee)', 'Olbrzymi porost (Swamp Fungal Pod)',
                                'Pióra wiedźmokruka (Hagraven Feathers)', 'Sole pustki (Void Salts)'}}


class DataSource:

    def __init__(self):
        self.effects_set = set(effect_to_ingredients_dict.keys())
        self.ingredients_set = set()
        for s in effect_to_ingredients_dict.values():
            for item in s:
                self.ingredients_set.add(item)
